let values = [[
    "salutations",
    "hello",
    "compliments",
    "best wishes",
    "regards",
    "respects",
    "congratulations",
    "howdy",
    "good wishes",
    "love",
    "greeting",
    "felicitations",
    "good day",
    "welcome",
    "good afternoon",
    "best",
    "hey",
    "what's up",
    "morning",
    "salute",
    "compliment",
    "hi",
    "hi there",
    "kind regards",
    "holla",
    "regard",
    "yo",
    "hiya",
    "how's it going",
    "salaam",
    "how goes it",
    "hey there",
    "what's happening",
    "respect",
    "g'day",
    "wassup",
    "say hello",
    "top of the morning",
    "hello there",
    "what's new",
    "greet",
    "say hi",
    "sup",
    "how are you",
    "howzit",
    "good evening",
    "well",
    "what ho",
    "good morning",
    "how's it hanging",
    "how are things",
    "why hello there",
    "saluted",
    "my regards",
    "my best",
    "a-yo",
    "hey, what's up",
    "kindest regards",
    "bonjour",
    "greets",
    "how do",
    "how you living",
    "how is it",
    "howsyamomanem",
    "look who it is",
    "look what the cat dragged in",
    "how are things with you",
    "what's happenin'",
    "well hello",
    "it's nice to meet you",
    "wassap",
    "it's a pleasure to meet you",
    "privet",
    "namaste",
    "warm wishes",
    "shalom",
    "hallo",
    "how ya goin",
    "it's good to see you",
    "how do you do",
    "salaam alaikum",
    "congrats",
    "hola",
    "commend",
    "hail",
    "saluting",
    "salutation",
    "greetings to",
    "how's everything",
    "hellos",
    "ciao",
    "give my love",
    "nothing but right",
    "i welcome",
    "blessings",
    "your regards",
    "receptions",
    "how are you doing",
    "hi-ya",
    "howdy-do",
    ],[
    "commended",
    "ahoy",
    "remembrances",
    "wotcher",
    "devoirs",
    "aloha",
    "yello",
    "handshake",
    "hullo",
    "congratulated",
    "good day to you",
    "ayo",
    "cheerio",
    "goodbye",
    "yeah",
    "konichiwa",
    "ey up",
    "his regards",
    "heyo",
    "what's going on",
    "heaveno",
    "heyday",
    "hails",
    "many happy returns",
    "i said hi",
    "shout-out",
    "welcomed",
    "wave",
    "wagwan",
    "ayubowan",
    "bid welcome",
    "say hello to",
    "wish",
    "bows",
    "curtsied",
    "salute the",
    "felicitation",
    "very softly",
    "as-salaam-alaikum",
    "as-salamu alaykum",
    "salam aleikum",
    "salvation",
    "bonsoir",
    "goodnight",
    "please remember me",
    "best regards",
    "every good wish",
    "yoo-hoo",
    "g'day mate",
    "how bist",
    "how's tricks",
    "peace offering",
    "alo",
    "gidday",
    "whoa",
    "lo",
    "how",
    "salaams",
    "shalom aleichem",
    "my compliments",
    "every success",
    "well met",
    "what's doing",
    "alright",
    "alright me babber",
    "alright me lover",
    "salutes",
    "ay up me duck",
    "ayoo",
    "welcomes",
    "hi ya",
    "your good-byes",
    "wish you luck",
    "congratulation",
    "i said hello",
    "his greetings",
    "skywalker",
    "bello",
    "truly yours",
    "buenos dias",
    "ni hao",
    "yours sincerely",
    "said hi",
    "call-up",
    "very best",
    "i greet",
    "your compliments",
    "handshakes",
    "cooee",
    "his compliments",
    "long time no see",
    "acknowledgments",
    "affirmations",
    "most welcome",
    "peekaboo",
    "warm regards",
    "hand",
    "as-salaam alaikum",
    "share",
    "their regards",
    ],
    [
    "said hello",
    "hellow",
    "greeted",
    "assalamu alaikum",
    "warmly",
    "cuckoo",
    "farewell",
    "heilo",
    "peek-a-boo",
    "you waved",
    "congratulating",
    "wotcha",
    "what's cooking",
    "greeting card",
    "sweet-talk",
    "you too",
    "peace",
    "sincerely",
    "giveaways",
    "softly",
    "you say hi",
    "induction",
    "pay tribute",
    "accosts",
    "how you doing",
    "remembrance",
    "pleased to meet you",
    "how have you been",
    "congratulates",
    "how are things going",
    "congratulate",
    "what are you up to",
    "say goodbye",
    "soft",
    "sends his regards",
    "says hello",
    "sends his greetings",
    "tribute",
    "sends his love",
    "kudos",
    "homage",
    "salvos",
    "allo",
    "compliments of the season",
    "saying goodbye",
    "says hi",
    "consolation",
    "he-hello",
    "your best",
    "toasts",
    "say hey",
    "your respects",
    "give my regards",
    "buenas noches",
    "afternoons",
    "you welcome",
    "your good wishes",
    "young skywalker",
    "curtsies",
    "your greetings",
    "blank cartridge",
    "mornin",
    "warmest greetings",
    "your truth",
    "great day",
    "impressment",
    "nice day",
    "good morrow",
    "what's up doc",
    "toast",
    "wishful thinking",
    "helillo",
    "well wishes",
    "applaud",
    "you said hello",
    "obeisances",
    "permissions",
    "very smoothly",
    "his",
    "say hello to people",
    "blank",
    "archaic devoirs",
    "commendation",
    "memorial",
    "salam alaikum",
    "hiss",
    "signals",
    "ho-hi",
    "empty cartridge",
    "accost",
    "honor",
    "acknowledge",
    "accredit",
    "said to say hi",
    "discern",
    "blank cartridge device",
    "salam",
    "distinguish",
    "praised",
    "realise",
    ],
    [
    "seiner",
    "how you been",
    "realize",
    "honour",
    "signs",
    "you going to say goodbye",
    "hi-ho",
    "say hello to the people",
    "recognise",
    "recognize",
    "satisfying",
    "happy new",
    "send my love",
    "heigh ho",
    "applause",
    "put your hands together",
    "how are ya",
    "so softly",
    "safety",
    "give her my best",
    "speak to people",
    "clap",
    "peaceful",
    "commend the",
    "salaam alaykum",
    "give it up",
    "olive branch",
    "make up",
    "dude",
    "seiners",
    "book signing",
    "for peace",
    "convey my regards",
    "wait",
    "autograph",
    "happy birthday",
    "make peace",
    "fulfilling",
    "acknowledge the",
    "greeting people",
    "card",
    "dedicated",
    "evenin",
    "making peace",
    "compliance",
    "you gonna say goodbye",
    "part",
    "you say hello",
    "dedicate",
    "just fine",
    "guarantee of peace",
    "fulfilment",
    "dedication",
    "enforcement",
    "good wish",
    "meeting",
    "welcome people",
    "pay tribute to the",
    "give him my regards",
    "send regards",
    "applauded",
    "just right",
    "mornings",
    "send their regards",
    "so gently",
    "congratulatory",
    "send greetings",
    "welcome the",
    "send their love",
    "say good-bye",
    "their blessing",
    "dedications",
    "gains",
    "hula",
    "heya",
    "formidable",
    "greet me",
    "heidilei",
    "nice afternoon",
    "ahoy there",
    "hala",
    "advantages",
    "very slow",
    "my love goes",
    "been eradicated",
    "shake hands",
    "you greet",
    "good morning to you",
    "give her my best wishes",
    "how you doin",
    "appreciation",
    "my highest",
    "really slow",
    "benefit",
    "say bye-bye",
    "sincerest wishes",
    "said to say hello",
    "real slow",
    "said to tell you hello",
    "fine",
    ],
    [
    "she said to say hi",
    "sure",
    "i send my love",
    "and say hello",
    "happiness",
    "good desire",
    "shake on it",
    "say hello to her",
    "commends the",
    "welcomes the",
    "say bye",
    "welcomed the",
    "fence",
    "applaud the",
    "their greetings",
    "hedge",
    "say good bye",
    "all the best",
    "greet the",
    "dabble in elixirs",
    "bye-bye",
    "i say hello",
    "salaam namaste",
    "well-wishers",
    "say hello to the",
    "have you said hello",
    "blessing",
    "get-well",
    "courtesy",
    "send you my love",
    "grip",
    "very gently",
    "good intentions",
    "welcoming the",
    "homages",
    "give her my regards",
    "all the better",
    "goodwill",
    "courtesies",
    "deference",
    "good mornin",
    "season's greetings",
    "kind wishes",
    "said good-bye",
    "you salute",
    "how goes",
    "my love",
    "his love",
    "good birthday",
    "shaking hands",
    "tributes",
    "happy anniversary",
    "reacts",
    "very soft",
    "happy return",
    "boon",
    "my love goes out",
    "very smooth",
    "success",
    "very mild",
    "good luck",
    "send her my love",
    "well done",
    "send my regards",
    "my humble respects",
    "say good night",
    "present",
    "cheers",
    "very quiet",
    "you said hi",
    "godsend",
    "tahani",
    "tell her i said hi",
    "and say hi",
    "offer of peace",
    "gonna say good-bye",
    "say goodbye to",
    "goodmorning",
    "highballs",
    "cordial greetings",
    "celebrate",
    "and say hello to",
    "i can wave",
    "howdies",
    "ahs",
    "how you gonna",
    "can i say hello",
    "interjections",
    "blessed",
    "my part",
    "my side",
    "very quietly",
    "gonna say goodbye",
    "i say goodbye",
    "my end",
    "say hi to",
    "my share",
    "say hello for me",
    "regards to",
    "i say hi",
    ],
    [
    "wish her well",
    "greet you",
    "thank",
    "facility",
    "peace offer",
    "cards",
    "establishing",
    "bless",
    "reporting",
    "preparation",
    "go say hi",
    "institution",
    "best to",
    "establishment",
    "top of the morning to you",
    "happening",
    "sky walker",
    "good night",
    "very slowly",
    "say hello to him",
    "let me say goodbye",
    "addresses",
    "bring you greetings",
    "warmest wishes",
    "advice",
    "bliss",
    "happened",
    "bulletin",
    "communication",
    "dirt",
    "sklywalkler",
    "information",
    "gestures",
    "really yours",
    "intelligence",
    "lowdown",
    "fraction",
    "message",
    "give my best",
    "news",
    "yours truly",
    "half",
    "notification",
    "be separated",
    "report",
    "tumbles",
    "cordially",
    "shout out",
    "reports",
    "rise and shine",
    "tidings",
    "warm greetings",
    "word",
    "allotment",
    "very good day",
    "assignment",
    "cordial",
    "greeter",
    "call of duty",
    "fine day",
    "howdy there",
    "call up",
    "warm",
    "really slowly",
    "very good morning",
    "greet people",
    "warmest regards",
    "happy returns",
    "lovely morning",
    "letter from uncle sam",
    "heigh-ho",
    "levy",
    "memories",
    "benediction",
    "fine morning",
    "lottery",
    "gonna say good bye",
    "military conscription",
    "memory",
    "beautiful morning",
    "recruiting",
    "top of the day",
    "really is yours",
    "registration",
    "souvenirs",
    "have a nice day",
    "roll call",
    "welcoming",
    "have a good day",
    "so long",
    "selective service",
    "appreciated",
    "blank cartridges",
    "this",
    "security",
    "early in the morning",
    "that",
    "send my greetings",
    "sincerely yours",
    "early morning",
    ],
    [
    "going to say goodbye",
    "i salute",
    "be welcomed",
    "early this morning",
    "salute to",
    "top of the morning to",
    "consolatory",
    "i will fire",
    "welcome back",
    "nods",
    "training cartridge",
    "benefits",
    "recognitions",
    "hey-ho",
    "agreement",
    "acknowledged",
    "wishes",
    ]]

export default values